// <auto-generated />
using System;
using BlockChain.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlockChain.Infrastructure.Migrations
{
    [DbContext(typeof(SaveOnlyBlockHistoryContext))]
    [Migration("20260920111402_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blockchain.Application.Models.BaseModels.BlockHistoryBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LastForkHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LastForkHeight")
                        .HasColumnType("integer");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PeerCount")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BlockHistory", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Blockchain.Application.Models.DefaultBlockHistoryModel", b =>
                {
                    b.HasBaseType("Blockchain.Application.Models.BaseModels.BlockHistoryBaseModel");

                    b.Property<int>("HighFeePerKb")
                        .HasColumnType("integer");

                    b.Property<int>("LowFeePerKb")
                        .HasColumnType("integer");

                    b.Property<int>("MediumFeePerKb")
                        .HasColumnType("integer");

                    b.ToTable("DefaultBlockHistory", (string)null);
                });

            modelBuilder.Entity("Blockchain.Application.Models.EtheriumBlockHistoryModel", b =>
                {
                    b.HasBaseType("Blockchain.Application.Models.BaseModels.BlockHistoryBaseModel");

                    b.Property<long>("HighGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("HighPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<long>("LowGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("LowPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<long>("MediumGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("MediumPriorityFee")
                        .HasColumnType("bigint");

                    b.ToTable("EtheriumBlockHistory", (string)null);
                });

            modelBuilder.Entity("Blockchain.Application.Models.DefaultBlockHistoryModel", b =>
                {
                    b.HasOne("Blockchain.Application.Models.BaseModels.BlockHistoryBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Blockchain.Application.Models.DefaultBlockHistoryModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blockchain.Application.Models.EtheriumBlockHistoryModel", b =>
                {
                    b.HasOne("Blockchain.Application.Models.BaseModels.BlockHistoryBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Blockchain.Application.Models.EtheriumBlockHistoryModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
